version: "3.9"
services:
        fastapi:
                container_name: "py"
                build: "./image/"
                ports:
                        - "80:80"
                volumes:
                        - "./image/app/:/app"
#        admin:
#                container_name: "dev"
#                image: pythonwithvim
#                volumes:
#                        - "minesweepercode:/app"
#                command: ["tail", "-f", "/dev/null"]
